{% set name = "mdsplus" %}
{% set version = "7.139.56" %}
{% set sha256 = "2e59ab6b28e1ddae7b46858c77eada882ff6acbab2cd79d66fa8ce7526876af6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/MDSplus/{{ name }}/archive/alpha_release-{{ version | replace('.','-') }}.tar.gz
  sha256: {{ sha256 }}

  patches:
    - python_MDSplus_setup.py.patch
    - tdishr_yylex_TdiHash.gen.patch
    - Makefile.inc.in.patch  # [osx]
build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - automake
    - autoconf
    - bison
    - flex
    - gperf
    - make
  host:
    - freetds 1.*
    - libiconv
    - libxml2
    - nose
    - numpy
    - perl
    - pip
    - pkg-config
    - python
    - readline
    - setuptools
    - zlib
  run:
    - freetds 1.*
    - numpy
    - python

test:
  imports:
    - MDSplus

about:
  home: http://www.mdsplus.org/
  license: MIT
  license_family: MIT
  license_file: MDSplus-License.txt
  summary: MDSplus data management system
  description: |
    MDSplus is a set of software tools for data acquisition and
    storage and a methodology for management of complex
    scientific data.

    MDSplus allows all data from an experiment or simulation
    code to be stored into a single, self-descriptive,
    hierarchical structure. The system was designed to enable
    users to easily construct complete and coherent data sets.

    The MDSplus programming interface contains only a few basic
    commands, simplifying data access even into complex
    structures. Using the client/server model, data at remote
    sites can be read or written without file transfers.
    MDSplus includes x-windows and java tools for viewing data
    or for modifying or viewing the underlying structures.
  dev_url: https://github.com/MDSplus/mdsplus

extra:
  recipe-maintainers:
    - smithsp
    - modestmc
