{% set name = "mdsplus" %}
{% set version = "7.7.15" %}
{% set sha256 = "37e0aa1d48f5aa279d80918039dc5538eb461e885828db8ee8e4f53992d4215c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/MDSplus/{{ name }}/archive/stable_release-{{ version | replace('.','-') }}.tar.gz
  sha256: {{ sha256 }}
  
  #Patches are mostly to correct /usr/local type explicit statements of dependencies  ; issue raised at https://github.com/MDSplus/mdsplus/issues/1201
  patches:
    - configure.patch.osx  # [osx]
    - configure.patch.linux  # [linux]
    - mdsdcl_show_version.c.patch
    - Makefile.in.patch

build:
  number: 0
  skip: True  # [win or py3k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - freetds 1.*
    - libxml2 2.9.*
    - perl 5.26.0
    - python
    - readline 7.*
    - setuptools
  run:
    - icu 58.*
    - libiconv 1.15.*
    - numpy
    - python
    - readline 7.*
    - xz 5.2.*

test:
  imports:
    - MDSplus

about:
  home: http://www.mdsplus.org/
  license: MIT
  license_family: MIT
  license_file: MDSplus-License.txt
  summary: MDSplus data management system
  description: |
    MDSplus is a set of software tools for data acquisition and
    storage and a methodology for management of complex
    scientific data.

    MDSplus allows all data from an experiment or simulation
    code to be stored into a single, self-descriptive,
    hierarchical structure. The system was designed to enable
    users to easily construct complete and coherent data sets.

    The MDSplus programming interface contains only a few basic
    commands, simplifyng data access even into complex
    structures. Using the client/server model, data at remote
    sites can be read or written without file transfers.
    MDSplus includes x-windows and java tools for viewing data
    or for modifying or viewing the underlying structures.
  dev_url: https://github.com/MDSplus/mdsplus

extra:
  recipe-maintainers:
    - smithsp
