travis:
  secure:
    BINSTAR_TOKEN: vJlBS8Xx51DvQxNlSsV2QJpHqcrpT5Iq+x+ztknZBgOLz8TyJHF+PV1WRsOV8ZIJq8gAvjHf2UqCgOamW3GlRUWpsbrhtmxxBZmjESmKQAuz52iO1PX0aYIW4LKc3v6TMt5PofbtrZvYIG1CMbJNLthsJRgEy+Qo6FbTgzrjhJMC6dgsp2D8GWwl36XU/Mw/2UxNErO2xHUCTrkRG6tgNCb5/IkJ6VH7q081pm/bhtx2qMmUPnBabzqp9Wtp2rZmPu33vYzlsC7MuBik9lKZnFNbpkKnA8RZn5WeA4RvdBLF4s1hEKYUvWjKpFQZ7RWznRyzdde5Sro1sC48Flnwy0vYoek5DPiz3a3SjWJwAviDYtskl0a+SXcn+YZ+znUdRJu+k0mscVKqIF3dbWhvlvrABDMzfGwAAjwXAF28lPwlhieEJDu3q6lFV3KRYKHRQU8yzjrtT/yvw2ZQCwQJGq6LLJCPtHa05JhyO/mZItF5CtWFbBxrnrYLANhNCe0Hzt22hXYyCmV6ZZcX0NS8EMHPcNd8IdxFxRrMHXy/O8wPEdfxoHS7bQaMfIhxf09WZBMGA0sdZ8156VkvSI7T3HUbkV2NetrhAz1SMuyyT5e2+Q5L+6VQPv81wfVyJjTDfK3tUOf2XZUBiMGKeqU7hD0n7uv/EEYe/iOm8kHazz4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
